[env]
_.python.venv = { path = ".venv", create = true }
_.file = ".env"

[tools]
python = "3.13"
uv = "latest"

[tasks.init]
description = "Install dependencies"
run = "uv sync --all-extras"

[tasks.lint]
run = "uv run ruff check . && uv run mypy ."

[tasks.format]
run = "uv run ruff format ."

[tasks.test]
run = "uv run pytest"

[tasks.app]
run = "uv run python -m streamlit run app/main.py"

[tasks.mcp-server]
run = "uv run python mcp_server/sample_server.py"

[tasks.mcp-client]
run = "uv run python mcp_server/sample_client.py"
